name: nih2mne-tests
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        #with:
                #Enode-version: '14'
      - run: sudo apt-get install datalad
      - run: datalad install https://github.com/OpenNeuroDatasets/ds004297.git
      - run: datalad get ./derivatives/sub-ON02747/ses-01/meg/
      - run: pip install pytest install git+https://github.com/nih-megcore/nih_to_mne
      - run: pytest -vv
